// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdWjogSHqqu02aKfysK-hM3ToZrbrBdcs',
    appId: '1:460977826406:web:617482183af9c415081ba7',
    messagingSenderId: '460977826406',
    projectId: 'face-lock-83ccc',
    authDomain: 'face-lock-83ccc.firebaseapp.com',
    storageBucket: 'face-lock-83ccc.firebasestorage.app',
    measurementId: 'G-FSHGH5JTX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDllR9RFXrDB5hiVjvwKMek_zMFMTnYrn0',
    appId: '1:460977826406:android:c4a6a087e8080f4e081ba7',
    messagingSenderId: '460977826406',
    projectId: 'face-lock-83ccc',
    storageBucket: 'face-lock-83ccc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClW_xEPq8luVPdSYGSEl4vv1Wje9_iBHA',
    appId: '1:460977826406:ios:bb4cf0269a66a937081ba7',
    messagingSenderId: '460977826406',
    projectId: 'face-lock-83ccc',
    storageBucket: 'face-lock-83ccc.firebasestorage.app',
    iosBundleId: 'com.example.faceLockerMobile',
  );
}
